my_name = ("ishaan")
my_age = (11)
your_name = input("What is your name: ")
your_age = input("what is your age: ")
print("hi  my name is ",my_name,"and i am ",my_age,"years old" )
print("hi there your name is ",your_name,"and you are ",your_age,"years old")
print("thanks for join us",your_name)